# Generated by Django 4.2.27 on 2025-12-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ckeditorupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremail',
            name='source',
            field=models.CharField(choices=[('contact', 'Kontakt forma'), ('registration', 'Registracija'), ('checkout', 'Porudžbina')], max_length=50, verbose_name='Izvor'),
        ),
    ]
