# Generated by Django 4.2.27 on 2025-12-24 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productdimension_productpattern_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productdimension', verbose_name='Izabrane dimenzije'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productpattern', verbose_name='Izabrani uzorak'),
        ),
    ]
