# Generated by Django 4.2.27 on 2025-12-25 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_productpattern_options_and_more'),
        ('accounts', '0002_orderitem_selected_dimension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='selected_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productpattern', verbose_name='Izabrani dezen'),
        ),
    ]
