# Generated by Django 4.2.27 on 2025-12-24 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Npr. "Standardne dimenzije"', max_length=200, verbose_name='Naziv dimenzija')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dužina (cm)')),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Širina (cm)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Visina (cm)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Redosled')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='shop.product')),
            ],
            options={
                'verbose_name': 'Dimenzije proizvoda',
                'verbose_name_plural': 'Dimenzije proizvoda',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Npr. "Drveni uzorak"', max_length=200, verbose_name='Naziv uzorka')),
                ('image', models.ImageField(upload_to='products/patterns/', verbose_name='Slika uzorka')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Redosled')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='shop.product')),
            ],
            options={
                'verbose_name': 'Uzorak proizvoda',
                'verbose_name_plural': 'Uzorci proizvoda',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='productattributevalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.DeleteModel(
            name='ProductAttributeValue',
        ),
    ]
