# Generated by Django 4.2.27 on 2025-12-24 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productdimension_productpattern_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productdimension',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productpattern',
            name='name',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
