# Generated by Django 4.2.27 on 2025-12-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_sale_price_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpattern',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Dezen proizvoda', 'verbose_name_plural': 'Dezeni proizvoda'},
        ),
        migrations.AlterField(
            model_name='productpattern',
            name='image',
            field=models.ImageField(upload_to='products/patterns/', verbose_name='Slika dezena'),
        ),
    ]
