# Generated by Django 4.2.27 on 2025-12-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_productpattern_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdimension',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ostavite prazno za "Na upit"', max_digits=10, null=True, verbose_name='Cena (RSD)'),
        ),
    ]
