# Generated by Django 4.2.27 on 2026-01-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_productpattern_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdimension',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Debljina (cm)'),
        ),
    ]
